package:
  name: orange3-datafusion
  version: "0.1.10"

source:
  fn: Orange3-DataFusion-0.1.10.tar.gz
  url: https://pypi.python.org/packages/13/e6/c916bb2f29388194dff8509ba955f714b05571b6d93c818cb736fb7a3637/Orange3-DataFusion-0.1.10.tar.gz
  md5: 08329e849dec5ab9893ac119ec903e37

build:
  script:
    - pip install --no-deps --no-cache ./

  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - setuptools
    - orange3 >=3.3.5
    - numpy
    - scikit-fusion
    - pyqt

test:
  # Python imports
  imports:
    - orangecontrib
    - orangecontrib.datafusion
    - orangecontrib.datafusion.tutorials
    - orangecontrib.datafusion.widgets

about:
  home: https://github.com/biolab/orange3-datafusion
  license: UNKNOWN
  summary: 'Orange DataFusion add-on.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
