package:
  name: orange3
  version: "3.3.3"

source:
  git_rev: 3.3.3
  git_url: https://github.com/biolab/orange3.git

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main

  osx_is_app: True

  script: pip install --no-deps --no-binary --no-cache ./

requirements:
  build:
    - python
    - setuptools
    # https://github.com/numpy/numpy/pull/6470
    - numpy         !=1.9.3   # [win]
    - numpy                   # [not win]
    - pip

  run:
    - python
    - setuptools
    - numpy         >=1.9.0
    - scipy
    - scikit-learn  >=0.16
    - bottlechest
    - chardet       >=2.3.0
    - docutils
    - xlrd          >=0.9.2
    - pyqt
    - pyqtgraph
    - joblib
    - python.app    # [osx]

test:
  # Python imports
  imports:
    - Orange
    - Orange.canvas
    - Orange.canvas.application
    - Orange.canvas.application.tutorials
    - Orange.canvas.canvas
    - Orange.canvas.canvas.items
    - Orange.canvas.document
    - Orange.canvas.gui
    - Orange.canvas.help
    - Orange.canvas.preview
    - Orange.canvas.registry
    - Orange.canvas.scheme
    - Orange.canvas.styles
    - Orange.canvas.utils

    - Orange.widgets
    - Orange.widgets.classify
    - Orange.widgets.data
    - Orange.widgets.evaluate
    - Orange.widgets.regression
    - Orange.widgets.unsupervised
    - Orange.widgets.visualize

    - Orange.classification
    - Orange.clustering
    - Orange.data
    - Orange.distance
    - Orange.evaluation
    - Orange.preprocess
    - Orange.projection
    - Orange.regression
    - Orange.statistics

  commands:
    - orange-canvas --help

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange, a component-based data mining framework.'
