package:
  name: orange3
  version: "3.3.8"

source:
  fn: Orange3-3.3.8.tar.gz
  url: https://pypi.python.org/packages/ad/ba/1bb39ab6698046c59363187fe7055b5e2b6ac5de89b0837a3af156cc58fc/Orange3-3.3.8.tar.gz
  md5: 72bea3c476855a29683ec9f53a1ca884

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main

  osx_is_app: True

  script:
    - python setup.py clean --all build -j1 bdist_wheel
    - if errorlevel 1 exit 1        # [win]
    - pip install --no-deps --no-cache --no-index -f dist Orange3
    - if errorlevel 1 exit 1        # [win]

requirements:
  build:
    - python
    - setuptools
    # https://github.com/numpy/numpy/pull/6470
    - numpy         ==1.9.2   # [win]
    - numpy         ==1.9.3   # [not win]

  run:
    - python
    - setuptools
    - numpy         >=1.9.0
    - scipy
    - scikit-learn  >=0.18
    - bottleneck
    - chardet       >=2.3.0
    - docutils
    - xlrd          >=0.9.2
    - pyqt          4.11.*
    - pyqtgraph
    - joblib
    - python.app    # [osx]

test:
  # Python imports
  imports:
    - Orange
    - Orange.canvas
    - Orange.canvas.application
    - Orange.canvas.canvas
    - Orange.canvas.canvas.items
    - Orange.canvas.document
    - Orange.canvas.gui
    - Orange.canvas.help
    - Orange.canvas.preview
    - Orange.canvas.registry
    - Orange.canvas.scheme
    - Orange.canvas.styles
    - Orange.canvas.utils

    - Orange.widgets
    - Orange.widgets.classify
    - Orange.widgets.data
    - Orange.widgets.evaluate
    - Orange.widgets.regression
    - Orange.widgets.unsupervised
    - Orange.widgets.visualize

    - Orange.classification
    - Orange.clustering
    - Orange.data
    - Orange.distance
    - Orange.evaluation
    - Orange.preprocess
    - Orange.projection
    - Orange.regression
    - Orange.statistics

  commands:
    - orange-canvas --help
    - python -m unittest Orange.tests

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange, a component-based data mining framework.'
