package:
  name: orange3
  version: "3.3.6"

source:
  fn: Orange3-3.3.6.tar.gz
  url: https://pypi.python.org/packages/31/b9/1aa1d3fe5a7fedace3895e79b21bc87e4993ed06c2b763bf9f1479575e21/Orange3-3.3.6.tar.gz
  md5: 569ffc6ba464641b1153ba3fd75567d2

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main

  osx_is_app: True

requirements:
  build:
    - python
    - setuptools
    # https://github.com/numpy/numpy/pull/6470
    - numpy         ==1.9.2   # [win]
    - numpy         ==1.9.3   # [not win]

  run:
    - python
    - setuptools
    - numpy         >=1.9.0
    - scipy
    - scikit-learn  >=0.17
    - bottlechest
    - chardet       >=2.3.0
    - docutils
    - xlrd          >=0.9.2
    - pyqt
    - pyqtgraph
    - joblib
    - python.app    # [osx]

test:
  # Python imports
  imports:
    - Orange
    - Orange.canvas
    - Orange.canvas.application
    - Orange.canvas.application.tutorials
    - Orange.canvas.canvas
    - Orange.canvas.canvas.items
    - Orange.canvas.document
    - Orange.canvas.gui
    - Orange.canvas.help
    - Orange.canvas.preview
    - Orange.canvas.registry
    - Orange.canvas.scheme
    - Orange.canvas.styles
    - Orange.canvas.utils

    - Orange.widgets
    - Orange.widgets.classify
    - Orange.widgets.data
    - Orange.widgets.evaluate
    - Orange.widgets.regression
    - Orange.widgets.unsupervised
    - Orange.widgets.visualize

    - Orange.classification
    - Orange.clustering
    - Orange.data
    - Orange.distance
    - Orange.evaluation
    - Orange.preprocess
    - Orange.projection
    - Orange.regression
    - Orange.statistics

  commands:
    - orange-canvas --help
    - python -m unittest Orange.tests

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange, a component-based data mining framework.'
