package:
  name: pyqtgraph
  version: "0.9.10"

source:
  fn: pyqtgraph-0.9.10.tar.gz
  url: https://pypi.python.org/packages/source/p/pyqtgraph/pyqtgraph-0.9.10.tar.gz
  md5: bd84bf7537c43cf38db81cc1ad4f743a

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - pyqt

test:
  # Python imports
  imports:
    - pyqtgraph
    - pyqtgraph.GraphicsScene
    # - pyqtgraph.canvas
    - pyqtgraph.console
    - pyqtgraph.dockarea
    # - pyqtgraph.examples
    # - pyqtgraph.examples.optics
    # - pyqtgraph.examples.relativity
    # - pyqtgraph.examples.verlet_chain
    - pyqtgraph.exporters
    - pyqtgraph.flowchart
    - pyqtgraph.flowchart.library
    - pyqtgraph.graphicsItems
    - pyqtgraph.graphicsItems.PlotItem
    - pyqtgraph.graphicsItems.ViewBox
    - pyqtgraph.imageview
    - pyqtgraph.metaarray
    - pyqtgraph.multiprocess
    # - pyqtgraph.opengl
    # - pyqtgraph.opengl.items
    - pyqtgraph.parametertree
    - pyqtgraph.pixmaps
    - pyqtgraph.util
    - pyqtgraph.util.colorama
    - pyqtgraph.widgets

about:
  home: http://www.pyqtgraph.org
  license: MIT License
  summary: 'Scientific Graphics and GUI Library for Python'
