package:
  name: bottlechest
  version: "0.7.1"

source:
  fn: Bottlechest-0.7.1.tar.gz
  url: https://pypi.python.org/packages/source/B/Bottlechest/Bottlechest-0.7.1.tar.gz
  md5: 272a8d9e65ee6e8b072d5da5656337e8

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - bottlechest

about:
  home: https://github.com/biolab/bottlechest
  license: BSD License
  summary: 'Fast NumPy array functions written in Cython'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
