package:
  name: orange-bioinformatics
  version: "2.6.19"

source:
  fn: Orange-Bioinformatics-2.6.19.tar.gz
  url: https://pypi.python.org/packages/2e/84/3a1717f40a3b9d0925fde57fe7451c169fe46a0d1ca6c76cdab7091d0316/Orange-Bioinformatics-2.6.19.tar.gz
  md5: 3b58f6eba7097b21aec626fa62aff8ab

build:
  script: pip install --no-deps --no-cache ./

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - six
    - genesis-pyapi >=1.1.2
    - slumber >=0.7.1
    - requests >=2.6.0
    - pyqtgraph                # [py3k]
    - pyqt
    - orange                   # [py2k]
    - orange3 >=3.3.5          # [py3k]


test:
  # Python imports
  imports:
    - orangecontrib
    - orangecontrib.bio
    - orangecontrib.bio.dicty
    - orangecontrib.bio.gene
    - orangecontrib.bio.geneset
    - orangecontrib.bio.kegg
    - orangecontrib.bio.kegg.entry
    - orangecontrib.bio.ncbi
    - orangecontrib.bio.utils
    - orangecontrib.bio.widgets              # [py2k]
    - orangecontrib.bio.widgets.prototypes   # [py2k]
    - orangecontrib.bio.widgets.utils        # [py2k]
    - orangecontrib.bio.widgets3             # [py3k]
    - orangecontrib.bio.widgets3.utils       # [py3k]


about:
  home: http://orange.biolab.si/download
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange Bioinformatics add-on for Orange data mining software package.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
