package:
  name: orange3-associate
  version: "1.1.2"

source:
  fn: Orange3-Associate-1.1.2.tar.gz
  url: https://pypi.python.org/packages/89/6a/47b2dde4a6226517052249978670a82c64c55cfe8c9e282d1a69ad1afe2f/Orange3-Associate-1.1.2.tar.gz
  md5: f12feec03f345a888523dff47f391e0b

build:
  script:
    - pip install --no-deps --no-cache ./

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - orange3

test:
  # Python imports
  imports:
    - orangecontrib
    - orangecontrib.associate
    - orangecontrib.associate.widgets

about:
  home: https://github.com/biolab/orange3-associate
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange add-on for mining frequent itemsets and association rules.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
